# Generated by Django 5.0.3 on 2026-06-02 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_on', models.DateField()),
                ('base_game', models.CharField(choices=[('uprising', 'Dune: Imperium — Uprising'), ('imperium', 'Dune: Imperium (original)')], default='uprising', max_length=20)),
                ('bloodlines', models.BooleanField(default=True, help_text='Bloodlines expansion was used')),
                ('player_count', models.PositiveSmallIntegerField(choices=[(2, '2 players'), (3, '3 players'), (4, '4 players'), (6, '6 players (team mode)')])),
                ('rounds', models.PositiveSmallIntegerField(blank=True, help_text='Number of rounds played (optional)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-played_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=80)),
                ('leader', models.CharField(blank=True, max_length=120)),
                ('victory_points', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='games.game')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='gameresult',
            constraint=models.UniqueConstraint(fields=('game', 'player_name'), name='unique_player_per_game'),
        ),
    ]
