# Generated by Django 5.0.3 on 2026-06-02 17:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('scoring_notes', models.TextField(blank=True, help_text='League scoring rules (admin; user-facing copy is stored as entered).')),
                ('scoring_config', models.JSONField(blank=True, default=dict, help_text='Structured scoring JSON — see games/scoring.py')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Total table time in minutes', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='alliance_bene_gesserit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='alliance_emperor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='alliance_fremen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='alliance_guild',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='sardaukar_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sardaukar commanders recruited (Bloodlines)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_count',
            field=models.PositiveSmallIntegerField(choices=[(2, '2 jugadores'), (3, '3 jugadores'), (4, '4 jugadores'), (6, '6 jugadores (equipos)')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='rounds',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of rounds played', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.league'),
        ),
    ]
