# Generated by Django 5.0.3 on 2026-06-04 12:25

import django.db.models.deletion
from django.db import migrations, models


def copy_manual_player_to_m2m(apps, schema_editor):
    LeagueHito = apps.get_model("games", "LeagueHito")
    for hito in LeagueHito.objects.filter(manual_player_id__isnull=False).iterator():
        hito.manual_players.add(hito.manual_player_id)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_simplify_league_hitos'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguehito',
            name='manual_players',
            field=models.ManyToManyField(blank=True, help_text='Powerscore holders (supports ties).', related_name='powerscore_hitos_multi', to='games.player'),
        ),
        migrations.AlterField(
            model_name='leaguehito',
            name='manual_player',
            field=models.ForeignKey(blank=True, help_text='Legacy single holder; synced from manual_players when saving via UI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerscore_hitos', to='games.player'),
        ),
        migrations.RunPython(copy_manual_player_to_m2m, migrations.RunPython.noop),
    ]
